// <auto-generated />
namespace Project4_EntityFrameworkCodeFirstMovieProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class categoryentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202409181829167_category-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
